/* Generated By:JavaCC: Do not edit this line. KnifeParserConstants.java */
package net.zerobone.knife.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KnifeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int LEFT_PAREN = 13;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 14;
  /** RegularExpression Id. */
  int BIG_ID = 15;
  /** RegularExpression Id. */
  int SMALL_ID = 16;
  /** RegularExpression Id. */
  int BIG_LETTER = 17;
  /** RegularExpression Id. */
  int SMALL_LETTER = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int CODE = 21;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\f\"",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 10>",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "<BIG_ID>",
    "<SMALL_ID>",
    "<BIG_LETTER>",
    "<SMALL_LETTER>",
    "<LETTER>",
    "<DIGIT>",
    "<CODE>",
  };

}
